### ISSUE TITLE
Tlog parse failed

### ISSUE THREAD

**Issue by JacobHagberg** [rmargar/pymavlog#36]
I have installed pymavlog using "pip3 install pymavlog". With this, I tested the tlog parser and had an error.
Python: 3.11.1
14 in M1 Mac
Sonoma 14.2.1

When I run the code:

from pymavlog import MavTLog

filepath = "/Users/jacobhagberg/Downloads/FSS Baseline Flight.tlog"
tlog = MavTLog(filepath)
tlog.parse()

I get the error:
Traceback (most recent call last):
  File "/Users/jacobhagberg/Documents/PythonCode/NavLogReading/PymavlogTest.py", line 5, in <module>
    tlog = MavTLog(filepath)
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymavlog/core.py", line 350, in __init__
    self.__set_parsed_data(types)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymavlog/core.py", line 362, in __set_parsed_data
    self._parsed_data[name] = MavLinkMessageSeries.from_message(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymavlog/core.py", line 132, in from_message
    msg_types = list(map(lambda x: cls.MSG_TYPES[x], msg.fieldtypes))
                                                     ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fieldtypes'

I just copy-pasted the example code from the GitHub page but it does not work. Any idea what is going wrong?

**Comment by JacobHagberg** [comment]
Upon further investigation, my log file appears to be not formated correctly, sorry about that.
